### ISSUE TITLE
Evaluation of trained EPI policy

### ISSUE THREAD

**Issue by parth-p** [zwxxxuan/EPI#1]
- Readme asks to run "evaluate_hopper_with_policy.py" but there is only a file by the name "evaluate.py".
- Also can someone help me out during evaluation where is interaction happening(using trajectory to get embedding)? Is it happening in env.reset.
Can you please help me out with these issues.

**Comment by Wenxuan-Zhou** [comment]
Hi,
1. It should be "evaluate.py". The typo has been corrected in README. Thank you for pointing this out.
2. Here is when the interaction is happening:
      https://github.com/Wenxuan-Zhou/EPI/blob/master/EPI/envs/hopper_task.py#L19
      https://github.com/Wenxuan-Zhou/EPI/blob/master/EPI/interaction_policy/epi_policy.py#L72

Let me know if you have any other questions.
